version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      - frontend-next:/app/.next
    environment:
      - NODE_ENV=development

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=gpx-data
      - POSTGRES_USER=jasper
      - POSTGRES_PASSWORD=postgres
      #- "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  frontend-node-modules:
  frontend-next:
  postgres-data:
