# got this from chatgpt, so it's probably not perfect :)

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - DB_HOST=postgres
      - DB_NAME=gpx-data
      - DB_USER=user
      - DB_PASSWORD=password

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=gpx-data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgres_data:
